version: '3.8'

services:
  # Redis 데이터베이스 서버 (Redis database server)
  redis-db:
    image: redis:alpine
    container_name: redis-db
    ports:
      - "6379:6379"

  # 게임 서버 1 (3001번 포트로 접속) (Game server 1 (connect on port 3001))
  server-alpha:
    build: ./Server
    environment:
      - PORT=3000
    depends_on:
      - redis-db

  # 게임 서버 2 (3002번 포트로 접속) (Game server 2 (connect on port 3002))
  server-beta:
    build: ./Server
    environment:
      - PORT=3000
    depends_on:
      - redis-db
  
  # 로드 밸런서 추가
  nginx:
    image: nginx:latest
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # 이제 사용자는 http://localhost (80포트)로 접속합니다.
    depends_on:
      - server-alpha
      - server-beta